# Generated by Django 5.2.7 on 2025-11-05 16:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_scheduleslot_options_provider_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='provider',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
